dataset:
  name: Cora
  save_path: ./data
model:
  name: "torch"
  latent_dim: 512
training:
  train_size_ratio: 0.8
  save_path: "./train_result"
  epochs: 1000
  verbose: 10
visualization:
  features:
    - loss
    - time
    - accuracy
  fig_path: ./visualization
  is_save: true
  fig_name: comparison
